sudo: required
services:
  - docker
before_install:
  - docker build -t raj/react-docker -f Dockerfile.dev .
script:
  - docker run raj/react-docker npm run test -- --coverage
#DockerReact-env.3zg2bkj2mi.eu-west-2.elasticbeanstalk.com
deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  backet_name: "elasticbeanstalk-eu-west-2-828779960805"
  backet_path:  "docker-react"
  on:
    branch: master
  accesss_key_id: "$Access_key_ID"
  secret_access_key:
    secure: "$Secret_access_key"